### ISSUE TITLE
Errro - No such field 'toJson'

### ISSUE THREAD

**Issue by vcottagiri** [jaccomoc/jactl#29]
Trying out the toJson support as described - https://jactl.io/language-guide#json-support

```
java -cp jactl-repl-1.2.0.jar io.jactl.repl.Repl     

> class Address { String street; String suburb; String state }
> class Employee { String name; int employeeId; Address homeAddress }
> def jim = new Employee('Jim Henderson', 1234, [street:'123 High St', suburb:'Downtown', state:'South Australia'])
> [name:'Jim Henderson', employeeId:1234, homeAddress:[street:'123 High St', suburb:'Downtown', state:'South Australia']]
[name:'Jim Henderson', employeeId:1234, homeAddress:[street:'123 High St', suburb:'Downtown', state:'South Australia']]
> jim.toJson()
No such field 'toJson' for type io.jactl.pkg.Employee @ line 1, column 5
jim.toJson()
    ^
```

**Comment by jaccomoc** [comment]
Hi,

The GitHub documentation is always based on the latest version (not sure if
it is possible to have different versions of the online documentation) and
the toJson() function did not exist in version 1.2.0.

If you build the latest version of the code the function will work or wait
until version 1.3 is released in a few days time.

Cheers,
James
