### ISSUE TITLE
Question - "Hello word" program never terminates

### ISSUE THREAD

**Issue by sykesd** [jaccomoc/jactl#78]
I am experimenting with Jactl as a potential end-user programming language in our system. It caught my eye because of the ability to completely sandbox the user scripts.

However, when I run a "Hello, world" program, as follows, it never terminates:
```java
package com.franke.pbs.scripting;

import io.jactl.Jactl;

public class Sample {
  public static void main(String[] args) {
    Object result = Jactl.eval("3 + 4");
    System.out.println("Hello, World! result = " + result + ", type = " + result.getClass().getName());
  }
}
```

It seems like the runtime infrastructure is starting some background daemon threads. Is there any way to terminate those?

More concretely, what background threads/resources are being started, and would they be shared by future calls to `Jactl.eval(...)`, or would each such call start new instances of those background threads/resources?

**Comment by jaccomoc** [comment]
By default, it will use a `io.jactl.DefaultEnv` object as its execution environment which creates two ExecutorService instances each with their own thread pool as well as a single-threaded ScheduledExecutorService for timers. At the moment it does not expose any mechanism for shutting these down at termination which presumably prevents the program terminating as it still has daemon threads running. The [Integration Guide](https://jactl.io/integration-guide) talks a little about this. I will look at adding a shutdown mechanism to clean this up.

**Comment by jaccomoc** [comment]
Forgot to mention that these thread pools are shared so no new ones will be created with future calls to `Jactl.eval()`.

**Comment by jaccomoc** [comment]
I have added a shutdown method to DefaultEnv, updated the [Integration Guide](https://jactl.io/integration-guide), and added an entry to the [FAQ](https://jactl.io/faq).

**Comment by sykesd** [comment]
Fantastic. Thank you.

**Comment by sykesd** [comment]
This answers my question.
